language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli
script:
  - grunt
  - grunt coverage
  - node node_modules/coveralls/bin/coveralls.js < build/reports/coverage/lcov.info
